name: Docker Image CI

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      tag_version:
        description: 'Docker Image Tag Version'
        required: true
        default: 'v0.1'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/mt7986-static-binaries:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/mt7986-static-binaries:${{ github.event.inputs.tag_version }}